# Generated by Django 6.0.3 on 2026-03-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Институт/школа')),
            ],
            options={
                'verbose_name': 'Институт/школа',
                'verbose_name_plural': 'Институты/школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код направления/специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления/специальности')),
            ],
            options={
                'verbose_name': 'Направление/специальность',
                'verbose_name_plural': 'Направления/специальности',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кафедра/департамент')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='references.institute', verbose_name='Институт/школа')),
            ],
            options={
                'verbose_name': 'Кафедра/департамент',
                'verbose_name_plural': 'Кафедры/департаменты',
                'ordering': ['institute__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('institute', 'name'), name='uniq_department_per_institute')],
            },
        ),
    ]
