# Generated by Django 6.0.3 on 2026-03-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='references.educationlevel', verbose_name='Уровень образования')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='references.institute', verbose_name='Институт/школа')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='references.specialty', verbose_name='Направление/специальность')),
            ],
            options={
                'verbose_name': 'Программа (доступность направления)',
                'verbose_name_plural': 'Программы (доступность направлений)',
                'constraints': [models.UniqueConstraint(fields=('institute', 'education_level', 'specialty'), name='uniq_program')],
            },
        ),
    ]
