# Generated by Django 6.0.3 on 2026-03-06 02:02

import apps.submissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_full_name', models.CharField(max_length=255, verbose_name='ФИО автора')),
                ('supervisor_full_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('work_title', models.CharField(max_length=500, verbose_name='Название работы')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('page_count', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('file', models.FileField(upload_to=apps.submissions.models.submission_upload_path, verbose_name='Файл (PDF)')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('file_extension', models.CharField(blank=True, max_length=16, verbose_name='Расширение файла')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('needs_fix', 'Требует исправлений'), ('accepted', 'Принято')], default='draft', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.department', verbose_name='Кафедра/департамент')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.documenttype', verbose_name='Тип документа')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.educationlevel', verbose_name='Уровень образования')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.institute', verbose_name='Институт/школа')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.specialty', verbose_name='Направление/специальность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
