# Generated by Django 6.0.3 on 2026-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='staff_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверяющего'),
        ),
    ]
